on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 * * * *"

name: Milwaukee weather update

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          # don't reinstall R
          install-r: false
          # use RStudio's CRAN mirror with precompiled binaries
          use-public-rspm: true
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Retrieve data
        run:  Rscript -e 'source("R/Retrieve_GHCN_USW00014839.R")'
      - name: Commit data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
      - name: Build graph
        run:  Rscript -e 'source("R/BuildDailyHigh.R")'
      - name: Commit graph
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
