on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 * * * *"

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          # don't reinstall R
          install-r: false
          # use RStudio's CRAN mirror with precompiled binaries
          use-public-rspm: true
      - name: Setupt revn cach
        uses: r-lib/actions/setup-renv@v2
      - name: Retrieve data
        run:  Rscript -e 'source("R/Retrieve_GHCN_USW00014839.R")'
      - name: Build graph
        run:  Rscript -e 'source("R/BuildDailyHigh.R")'
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
